# Autogenerated. Do not edit. 

set(arduinolibs_Adafruit_nRF52 Adafruit_LittleFS;Adafruit_TinyUSB_Arduino;Adafruit_nRFCrypto;BLEAdafruitService;BLEHomekit;Bluefruit52Lib;InternalFileSytem;PDM;RotaryEncoder;SPI;Servo;SoftwareSerial;Wire)

set(arduinolib_Adafruit_LittleFS_srcs
    Adafruit_nRF52_Arduino/libraries/Adafruit_LittleFS/src/Adafruit_LittleFS.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_LittleFS/src/littlefs/lfs.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_LittleFS/src/littlefs/lfs_util.c
)

set(arduinolib_Adafruit_LittleFS_incs
    Adafruit_nRF52_Arduino/libraries/Adafruit_LittleFS/src
)

set(arduinolib_Adafruit_TinyUSB_Arduino_srcs
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/arduino/Adafruit_TinyUSB_API.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/arduino/Adafruit_USBD_CDC.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/arduino/Adafruit_USBD_Device.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/arduino/hid/Adafruit_USBD_HID.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/arduino/midi/Adafruit_USBD_MIDI.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/arduino/msc/Adafruit_USBD_MSC.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/arduino/ports/esp32/Adafruit_TinyUSB_esp32.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/arduino/ports/nrf/Adafruit_TinyUSB_nrf.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/arduino/ports/rp2040/Adafruit_TinyUSB_rp2040.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/arduino/ports/samd/Adafruit_TinyUSB_samd.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/arduino/webusb/Adafruit_USBD_WebUSB.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/class/audio/audio_device.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/class/bth/bth_device.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/class/cdc/cdc_device.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/class/dfu/dfu_device.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/class/dfu/dfu_rt_device.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/class/hid/hid_device.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/class/midi/midi_device.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/class/msc/msc_device.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/class/net/ecm_rndis_device.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/class/net/ncm_device.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/class/usbtmc/usbtmc_device.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/class/vendor/vendor_device.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/common/tusb_fifo.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/device/usbd.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/device/usbd_control.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/portable/espressif/esp32sx/dcd_esp32sx.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/portable/microchip/samd/dcd_samd.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/portable/nordic/nrf5x/dcd_nrf5x.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/portable/nxp/transdimension/dcd_transdimension.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/portable/raspberrypi/rp2040/dcd_rp2040.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/portable/raspberrypi/rp2040/hcd_rp2040.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/portable/raspberrypi/rp2040/rp2040_usb.c
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src/tusb.c
)

set(arduinolib_Adafruit_TinyUSB_Arduino_incs
    Adafruit_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/src
)

set(arduinolib_Adafruit_nRFCrypto_srcs
    Adafruit_nRF52_Arduino/libraries/Adafruit_nRFCrypto/src/Adafruit_nRFCrypto.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_nRFCrypto/src/ecc/nRFCrypto_ECC.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_nRFCrypto/src/ecc/nRFCrypto_ECC_PrivateKey.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_nRFCrypto/src/ecc/nRFCrypto_ECC_PublicKey.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_nRFCrypto/src/nRFCrypto_Hash.cpp
    Adafruit_nRF52_Arduino/libraries/Adafruit_nRFCrypto/src/nRFCrypto_Random.cpp
)

set(arduinolib_Adafruit_nRFCrypto_incs
    Adafruit_nRF52_Arduino/libraries/Adafruit_nRFCrypto/src
)

set(arduinolib_BLEAdafruitService_srcs
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src/services/BLEAdafruitAccel.cpp
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src/services/BLEAdafruitAddressablePixel.cpp
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src/services/BLEAdafruitBaro.cpp
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src/services/BLEAdafruitButton.cpp
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src/services/BLEAdafruitColor.cpp
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src/services/BLEAdafruitGesture.cpp
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src/services/BLEAdafruitGyro.cpp
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src/services/BLEAdafruitHumid.cpp
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src/services/BLEAdafruitLightSensor.cpp
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src/services/BLEAdafruitMagnetic.cpp
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src/services/BLEAdafruitProximity.cpp
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src/services/BLEAdafruitQuaternion.cpp
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src/services/BLEAdafruitSensor.cpp
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src/services/BLEAdafruitSound.cpp
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src/services/BLEAdafruitTemperature.cpp
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src/services/BLEAdafruitTone.cpp
)

set(arduinolib_BLEAdafruitService_incs
    Adafruit_nRF52_Arduino/libraries/BLEAdafruitService/src
)

set(arduinolib_BLEHomekit_srcs
    Adafruit_nRF52_Arduino/libraries/BLEHomekit/src/BLEHomekit.cpp
    Adafruit_nRF52_Arduino/libraries/BLEHomekit/src/HAPCharacteristic.cpp
    Adafruit_nRF52_Arduino/libraries/BLEHomekit/src/HAPProcedure.cpp
    Adafruit_nRF52_Arduino/libraries/BLEHomekit/src/HAPService.cpp
    Adafruit_nRF52_Arduino/libraries/BLEHomekit/src/crypto/crypto.c
    Adafruit_nRF52_Arduino/libraries/BLEHomekit/src/crypto/random.c
    Adafruit_nRF52_Arduino/libraries/BLEHomekit/src/crypto/srp/bignum.c
    Adafruit_nRF52_Arduino/libraries/BLEHomekit/src/crypto/srp/memory_buffer_alloc.c
    Adafruit_nRF52_Arduino/libraries/BLEHomekit/src/crypto/srp/platform.c
    Adafruit_nRF52_Arduino/libraries/BLEHomekit/src/crypto/srp/srp.c
    Adafruit_nRF52_Arduino/libraries/BLEHomekit/src/crypto/tweetnacl-modified/tweetnacl.c
    Adafruit_nRF52_Arduino/libraries/BLEHomekit/src/service/HAPAccessoryInfo.cpp
    Adafruit_nRF52_Arduino/libraries/BLEHomekit/src/service/HAPLightBulb.cpp
    Adafruit_nRF52_Arduino/libraries/BLEHomekit/src/service/HAPPairing.cpp
    Adafruit_nRF52_Arduino/libraries/BLEHomekit/src/service/HAPProtocol.cpp
)

set(arduinolib_BLEHomekit_incs
    Adafruit_nRF52_Arduino/libraries/BLEHomekit/src
)

set(arduinolib_Bluefruit52Lib_srcs
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/BLEAdvertising.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/BLECentral.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/BLECharacteristic.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/BLEClientCharacteristic.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/BLEClientService.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/BLEConnection.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/BLEDiscovery.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/BLEGatt.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/BLEPeriph.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/BLEScanner.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/BLESecurity.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/BLEService.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/BLEUuid.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/bluefruit.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/clients/BLEAncs.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/clients/BLEClientBas.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/clients/BLEClientCts.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/clients/BLEClientDis.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/clients/BLEClientHidAdafruit.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/clients/BLEClientUart.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/services/BLEBas.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/services/BLEBeacon.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/services/BLEDfu.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/services/BLEDis.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/services/BLEHidAdafruit.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/services/BLEHidGamepad.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/services/BLEHidGeneric.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/services/BLEMidi.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/services/BLEUart.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/services/EddyStone.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/utility/AdaMsg.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/utility/bonding.cpp
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src/utility/bootloader_util.c
)

set(arduinolib_Bluefruit52Lib_incs
    Adafruit_nRF52_Arduino/libraries/Bluefruit52Lib/src
)

set(arduinolib_InternalFileSytem_srcs
    Adafruit_nRF52_Arduino/libraries/InternalFileSytem/src/InternalFileSystem.cpp
    Adafruit_nRF52_Arduino/libraries/InternalFileSytem/src/flash/flash_cache.c
    Adafruit_nRF52_Arduino/libraries/InternalFileSytem/src/flash/flash_nrf5x.c
)

set(arduinolib_InternalFileSytem_incs
    Adafruit_nRF52_Arduino/libraries/InternalFileSytem/src
)

set(arduinolib_PDM_srcs
    Adafruit_nRF52_Arduino/libraries/PDM/src/PDM.cpp
    Adafruit_nRF52_Arduino/libraries/PDM/src/utility/PDMDoubleBuffer.cpp
)

set(arduinolib_PDM_incs
    Adafruit_nRF52_Arduino/libraries/PDM/src
)

set(arduinolib_RotaryEncoder_srcs
    Adafruit_nRF52_Arduino/libraries/RotaryEncoder/RotaryEncoder.cpp
    Adafruit_nRF52_Arduino/libraries/RotaryEncoder/SwRotaryEncoder.cpp
)

set(arduinolib_RotaryEncoder_incs
    Adafruit_nRF52_Arduino/libraries/RotaryEncoder
)

set(arduinolib_SPI_srcs
    Adafruit_nRF52_Arduino/libraries/SPI/SPI.cpp
    Adafruit_nRF52_Arduino/libraries/SPI/SPI_nrf52832.cpp
)

set(arduinolib_SPI_incs
    Adafruit_nRF52_Arduino/libraries/SPI
)

set(arduinolib_Servo_srcs
    Adafruit_nRF52_Arduino/libraries/Servo/src/nrf52/Servo.cpp
)

set(arduinolib_Servo_incs
    Adafruit_nRF52_Arduino/libraries/Servo/src
)

set(arduinolib_SoftwareSerial_srcs
    Adafruit_nRF52_Arduino/libraries/SoftwareSerial/SoftwareSerial.cpp
)

set(arduinolib_SoftwareSerial_incs
    Adafruit_nRF52_Arduino/libraries/SoftwareSerial
)

set(arduinolib_Wire_srcs
    Adafruit_nRF52_Arduino/libraries/Wire/Wire_nRF52.cpp
)

set(arduinolib_Wire_incs
    Adafruit_nRF52_Arduino/libraries/Wire
)

